version: '2'
services:
  mongodb:
    image: "mongo:3.4"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=bd0
     - MONGO_INITDB_DATABASE=bdo
    ports:
     - "27017:27017"
  elasticsearch:
    build: "./elasticsearch"
    ports:
     - 9200:9200
  fuseki:
    build: "./fuseki"
    ports:
     - 3030:3030
    environment:
     - ADMIN_PASSWORD=bd0
  lov:
    build: "./lov"
    ports:
     - 3333:3333
    links:
     - mongodb
     - elasticsearch
     - fuseki
